version: "3.9"

services:
  # service zookeeper
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        ports:
        - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVER_ID: 1
        volumes:
        - ./data/zookeeper:/var/lib/zookeeper
        networks:
        - polylink-network

  #service kafka
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
        - 9092:9092
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

        volumes:
        - ./data/kafka:/var/lib/kafka
        networks:
        - polylink-network
        depends_on:
        - zookeeper

networks:
    polylink-network:
        name: polylink-network
        external: true